### ISSUE TITLE
`latest_version` is merely incremented instead of making the newest version the latest version.

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-meshify#199]
### Describe the bug

`latest_version` is merely incremented instead of making the newest version the latest version.

### Steps to reproduce

Start with `models/_models.yml`:

```yaml
models:
  - name: my_model
    latest_version: 2
    versions:
      - v: 1
      - v: 2
      - v: 3
      - v: 4
      - v: 5
```

And relevant `models/my_model_v*.sql` files like this:

```sql
select 1 as id
```

### Expected results

Based on this documentation:
```
$ dbt-meshify version --help                    
Usage: dbt-meshify version [OPTIONS]

  Increment the models to the next version, and create in the initial version
  if it has not yet been defined.

Options:
  -l, --latest         Makes the newest version the latest version when
                       incrementing model versions
```

I'd expect to get this:
```yaml
models:
  - name: my_model
    latest_version: 6
    versions:
      - v: 1
      - v: 2
      - v: 3
      - v: 4
      - v: 5
      - v: 6
```

### Actual results

```yaml
models:
  - name: my_model
    latest_version: 3
    versions:
      - v: 1
      - v: 2
      - v: 3
      - v: 4
      - v: 5
      - v: 6
```

### System information
**Which database are you using dbt with?**
- [x] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt debug`:**
```
<output goes here>
```

**The output of `dbt --version`:**
```
<output goes here>
```
