### ISSUE TITLE
DBT Meshify should add data_type precision that is defined in the database.

### ISSUE THREAD

**Issue by marcilj** [dbt-labs/dbt-meshify#215]
### Describe the feature
When we use `dbt-meshify` and it create the `yml` file for the models, it should configure the data_type with the proper precision.

```
version: 2

models:
  - name: my_model

    columns:
      - name: my_numeric_col1
        data_type: number(38,13)
      - name: my_numeric_col2
        data_type: number(38,16)
```

Instead of the current version
```
version: 2

models:
  - name: my_model

    columns:
      - name: my_numeric_col1
        data_type: number
      - name: my_numeric_col2
        data_type: number
```
