### ISSUE TITLE
YML dumping formatting

### ISSUE THREAD

**Issue by dave-connors-3** [dbt-labs/dbt-meshify#49]
Right now, the yml dumping logic does not follow our YML style guide. 

sample dictionary:
```json
{
    "my_items": [
        {
            "name": "item1",
            "price": 100
        },
        {
            "name": "item2",
            "price": 200
        },
        {
            "name": "item3",
            "price": 300
        }
    ]
}
```

curernt yml output:
```yml
my_items:
- name: item1
  price: 100
- name: item2
  price: 200
- name: item3
  price: 300
```

The output should be indented for arrays to more accurately represent the hierarchy:

```yml
my_items:
  - name: item1
    price: 100
  - name: item2
    price: 200
  - name: item3
    price: 300
```

May require some investigation into `pyyaml` options (i tried `indent` and `width` to no avail) or a new package altogether
