### ISSUE TITLE
duplicate versions defined after using `--prerelease` flag for version operation

### ISSUE THREAD

**Issue by dave-connors-3** [dbt-labs/dbt-meshify#90]
### Describe the bug

when using the `add-version` operation, if you use the `--prerelease` flag, which skips the `latest_version:` increment, and creates a file, the latest version and the defined versions are intentionally our of sync. Subsequent invocations of the add-version command after having used the --pre-release flag result in duplicated version numbers in yml. 

### Steps to reproduce

1. invoke `dbt-meshify operation add-version -s my_model`

yml result:

```
models: 
```
  - name: my_model
    latest_version: 1
    versions:
      - v: 1
```

2. invoke `dbt-meshify operation add-version -s my_model --prerelease`

yml result:

```
models: 
```
  - name: my_model
    latest_version: 1
    versions:
      - v: 1
      - v: 2
```
no error

1. invoke `dbt-meshify operation add-version -s my_model`

yml result:

```
models: 
  - name: my_model
    latest_version: 2
    versions:
      - v: 1
      - v: 2
      - v: 2
```
duplicate version entry

### Expected results

The add version command should
1. (no prerelease flag) increment `latest_version` and create next version + file based on defined yml versions
2. (prerelease flag) _not_ increment `latest_version` and still create next version + file based on defined yml versions

no parse errors from dbt

### Actual results

dupe versions and a parse error to boot

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt debug`:**
```
<output goes here>
```

**The output of `dbt --version`:**
```
<output goes here>
```
